CREATE TABLE ADMIN (USERNAME VARCHAR(10) PRIMARY KEY, PASSWORD VARCHAR(10));
CREATE TABLE CUSTOMER(PHONE_NUMBER VARCHAR(10) PRIMARY KEY, NAME VARCHAR(10) , ADDRESS VARCHAR(10));
CREATE TABLE CAR (REGISTRATION_NUMBER VARCHAR(10) PRIMARY KEY , OWNER VARCHAR(10) , MODEL VARCHAR(15) , DATE_OF_PURCHASE date);
CREATE TABLE ACCESSORIES (ID VARCHAR(4) PRIMARY KEY, NAME VARCHAR(15) , STOCK SMALLINT , PRICE MEDIUMINT);
CREATE TABLE INSTALLATION (ID VARCHAR(4) , ACCESSORY_ID VARCHAR(4) , CAR_REGISTRATION_NUMBER VARCHAR(10) , DATE_OF_INSTALLATION date);


INSERT INTO ADMIN VALUES('a','a');
select * from admin;